import type { Question, SourceDocument } from "./types";

export const demoDocuments: SourceDocument[] = [
  {
    id: "demo",
    name: "2025 届九年级第二次模拟考试·数学",
    subject: "数学",
    grade: "九年级",
    pageCount: 8,
    status: "reviewing",
    createdAt: "今天 09:42",
    questionCount: 24,
    approvedCount: 18,
  },
  {
    id: "physics-2",
    name: "高三物理二模综合卷（二）",
    subject: "物理",
    grade: "高三",
    pageCount: 12,
    status: "complete",
    createdAt: "昨天 16:20",
    questionCount: 18,
    approvedCount: 18,
  },
  {
    id: "english-1",
    name: "九年级英语二模答案与解析",
    subject: "英语",
    grade: "九年级",
    pageCount: 10,
    status: "extracting",
    createdAt: "昨天 11:03",
    questionCount: 0,
    approvedCount: 0,
  },
];

export const demoQuestions: Question[] = [
  {
    id: "q-01",
    number: "1",
    type: "single",
    stem: "计算 $|-3|+2^2$ 的结果是（　）",
    options: [
      { key: "A", content: "$-1$" },
      { key: "B", content: "$1$" },
      { key: "C", content: "$5$" },
      { key: "D", content: "$7$" },
    ],
    answer: "D",
    analysis: "$|-3|=3$，$2^2=4$，所以原式 $=3+4=7$。",
    page: 1,
    bbox: { x: 7.6, y: 22, width: 84.5, height: 12.5 },
    assets: [],
    tags: ["实数", "基础运算"],
    confidence: 0.98,
    status: "approved",
    score: 3,
  },
  {
    id: "q-02",
    number: "2",
    type: "single",
    stem: "如图，直线 $a\\parallel b$，$\\angle 1=56^\\circ$，则 $\\angle 2$ 的度数为（　）",
    options: [
      { key: "A", content: "$34^\\circ$" },
      { key: "B", content: "$56^\\circ$" },
      { key: "C", content: "$124^\\circ$" },
      { key: "D", content: "$134^\\circ$" },
    ],
    answer: "C",
    analysis: "由平行线性质及邻补角关系，$\\angle 2=180^\\circ-56^\\circ=124^\\circ$。",
    page: 1,
    bbox: { x: 7.4, y: 35.8, width: 84.8, height: 23.5 },
    assets: [
      {
        id: "asset-lines",
        kind: "figure",
        page: 1,
        bbox: { x: 58, y: 40.1, width: 28.2, height: 15.8 },
        label: "平行线几何图",
      },
    ],
    tags: ["平行线", "几何图形", "选择题"],
    confidence: 0.86,
    status: "needs_attention",
    score: 3,
  },
  {
    id: "q-03",
    number: "3",
    type: "fill",
    stem: "若关于 $x$ 的一元二次方程 $x^2-2x+m=0$ 有两个相等的实数根，则 $m=$ ____。",
    answer: "$1$",
    analysis: "判别式 $\\Delta=(-2)^2-4m=0$，解得 $m=1$。",
    page: 1,
    bbox: { x: 7.5, y: 61.5, width: 84.7, height: 9.7 },
    assets: [],
    tags: ["一元二次方程", "判别式"],
    confidence: 0.95,
    status: "pending",
    score: 3,
  },
  {
    id: "q-04",
    number: "4",
    type: "answer",
    stem: "如图，在 $\\triangle ABC$ 中，$AB=AC$，点 $D$ 在边 $BC$ 上。证明：$\\angle BAD=\\angle CAD$。",
    answer: "见证明过程",
    analysis: "连接相关辅助线，利用三边对应相等证明两个三角形全等，进而得到对应角相等。",
    page: 1,
    bbox: { x: 7.5, y: 73.2, width: 84.7, height: 20.5 },
    assets: [
      {
        id: "asset-triangle",
        kind: "figure",
        page: 1,
        bbox: { x: 60.5, y: 77.2, width: 22.5, height: 13.2 },
        label: "等腰三角形示意图",
      },
    ],
    tags: ["全等三角形", "证明题"],
    confidence: 0.91,
    status: "pending",
    score: 8,
  },
  {
    id: "q-05",
    number: "5",
    type: "single",
    stem: "一次函数 $y=kx+b$ 的图象如图所示，则下列判断正确的是（　）",
    options: [
      { key: "A", content: "$k>0,b>0$" },
      { key: "B", content: "$k>0,b<0$" },
      { key: "C", content: "$k<0,b>0$" },
      { key: "D", content: "$k<0,b<0$" },
    ],
    answer: "C",
    analysis: "图象从左向右下降，故 $k<0$；与 $y$ 轴交于正半轴，故 $b>0$。",
    page: 2,
    bbox: { x: 7, y: 18, width: 85, height: 23 },
    assets: [
      {
        id: "asset-graph",
        kind: "graph",
        page: 2,
        bbox: { x: 60, y: 21, width: 25, height: 17 },
        label: "一次函数图象",
      },
    ],
    tags: ["一次函数", "函数图象"],
    confidence: 0.89,
    status: "approved",
    score: 3,
  },
  {
    id: "q-06",
    number: "16",
    type: "answer",
    stem: "某校为了解学生每天课外阅读时间，随机调查了 $50$ 名学生，请根据频数分布表回答问题。",
    answer: "（1）$12$；（2）$36\%$；（3）估计约有 $720$ 人。",
    analysis: "先根据各组频数补全总数，再用样本比例估计总体人数。",
    page: 5,
    bbox: { x: 7, y: 23, width: 86, height: 34 },
    assets: [],
    tags: ["统计", "频数分布", "解答题"],
    confidence: 0.94,
    status: "approved",
    score: 8,
  },
  {
    id: "q-07",
    number: "22",
    type: "answer",
    stem: "已知抛物线 $y=ax^2+bx+c$ 经过点 $A(-1,0)$、$B(3,0)$、$C(0,3)$。（1）求抛物线解析式；（2）求面积最大值。",
    answer: "$y=-x^2+2x+3$；最大面积为 $8$。",
    analysis: "用待定系数法求解析式，再建立面积关于动点横坐标的二次函数并求顶点值。",
    page: 7,
    bbox: { x: 7, y: 19, width: 86, height: 51 },
    assets: [],
    tags: ["二次函数", "最值", "综合题"],
    confidence: 0.84,
    status: "pending",
    score: 12,
  },
  {
    id: "q-08",
    number: "24",
    type: "answer",
    stem: "在矩形 $ABCD$ 中，点 $P$ 沿边运动，探究线段长度与面积之间的函数关系。",
    answer: "分类讨论，详见解析。",
    analysis: "按点 $P$ 所在边分段建立函数关系，并验证各区间端点。",
    page: 8,
    bbox: { x: 7, y: 17, width: 86, height: 69 },
    assets: [],
    tags: ["动态几何", "分类讨论", "压轴题"],
    confidence: 0.78,
    status: "needs_attention",
    score: 14,
  },
];

export const typeLabels = {
  single: "单选题",
  multiple: "多选题",
  fill: "填空题",
  answer: "解答题",
} as const;
